# Generated by Django 5.0.4 on 2026-02-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('started', 'Started'), ('finished', 'Finished'), ('failed', 'Failed')], default='created', max_length=20),
        ),
    ]
